import "./globals.css";
import { Inter } from "next/font/google";
import { ClerkProvider } from "@clerk/nextjs";
import { SupabaseProvider } from "@/context/supabaseContext";
import { SignedIn, SignedOut } from "@clerk/nextjs/app-beta";
import Script from "next/script";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ClerkProvider>
          <SignedIn>
            <SupabaseProvider>{children} </SupabaseProvider>
          </SignedIn>
          <SignedOut>{children}</SignedOut>
        </ClerkProvider>
      </body>
    </html>
  );
}
