import "./globals.css";
import { Inter } from "next/font/google";
import { ClerkLoaded, ClerkProvider, SignedIn, SignedOut } from "@clerk/nextjs";
import { SupabaseProvider } from "@/context/supabaseContext";
import { ReactNode } from "react";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: ReactNode }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ClerkProvider
          publishableKey={process.env.NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY}
        >
          <SignedIn>
            <ClerkLoaded>
              <SupabaseProvider>{children} </SupabaseProvider>
            </ClerkLoaded>
          </SignedIn>
        </ClerkProvider>

        <SignedOut>{children}</SignedOut>
      </body>
    </html>
  );
}
